const adjectives = [
    "Adorable",
    "Beautiful",
    "Big",
    "Bright",
    "Clean",
    "Clever",
    "Cool",
    "Cute",
    "Cunning",
    "Determined",
    "Energetic",
    "Efficient",
    "Fantastic",
    "Fast",
    "Fine",
    "Fresh",
    "Good",
    "Gorgeous",
    "Great",
    "Handsome",
    "Hot",
    "Kind",
    "Lovely",
    "Mystic",
    "Neat",
    "Nice",
    "Patient",
    "Pretty",
    "Powerful",
    "Rich",
    "Secret",
    "Smart",
    "Solid",
    "Special",
    "Strategic",
    "Strong",
    "Tidy",
    "Wise"
];

const fruits = [
    "Apple",
    "Avocado",
    "Banana",
    "Blackberry",
    "Blueberry",
    "Broccoli",
    "Carrot",
    "Cherry",
    "Coconut",
    "Grape",
    "Lemon",
    "Lettuce",
    "Mango",
    "Melon",
    "Mushroom",
    "Onion",
    "Orange",
    "Papaya",
    "Peach",
    "Pear",
    "Pineapple",
    "Potato",
    "Pumpkin",
    "Raspberry",
    "Strawberry",
    "Tomato"
];

export function generateRandomAlias(): string {
    console.log(`Entropy: ${adjectives.length * fruits.length}`);
    const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
    const fruit = fruits[Math.floor(Math.random() * fruits.length)];
    return `${adjective} ${fruit}`;
}
